# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Jams's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@jamsethoth"

# Tagline section text
tagline: >
    Hey, I'm Jams, and I'm a cat dad and avid gamer! I've always loved video games and board games, and figured I could share that love and build a community by streaming.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - link:
      icon: "fa-brands fa-twitch"
      url: "https://www.twitch.tv/jamsethoth"
      alt: "Jams's Twitch Channel"
      title: "Jams's Twitch Channel"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@jamsethoth"
      alt: "Jams's YouTube Channel"
      title: "Jams's YouTube Channel"
      target: "_blank"
  - link:
      icon: "fa-solid fa-kickstarter"
      url: "https://kick.com/jamsethoth"
      alt: "Jams's Kick Channel"
      title: "Jams's Kick Channel"
      target: "_blank"
  - link:
      icon: "fa-solid fa-tiktok"
      url: "https://www.tiktok.com/@jamsethoth"
      alt: "Jams's Tiktok"
      title: "Jams's Tiktok"
      target: "_blank"
  - link:
      icon: "fa-solid fa-tiktok"
      url: "https://www.tiktok.com/@jamsethoth"
      alt: "Jams's Tiktok"
      title: "Jams's Tiktok"
      target: "_blank"
  - link:
      icon: "fa-solid fa-instagram"
      url: "https://www.instagram.com/jamseth0th/"
      alt: "Jams's Tiktok"
      title: "Jams's Tiktok"
      target: "_blank"
  - link:
      icon: "fa-solid fa-bluesky"
      url: "https://bsky.app/profile/jamsethoth.bsky.social"
      alt: "Jams's Bluesky"
      title: "Jams's Bluesky"
      target: "_blank"
  - link:
      icon: "fa-solid fa-twitter"
      url: "https://x.com/jamsethoth/"
      alt: "Jams's Twitter"
      title: "Jams's Twitter"
      target: "_blank"

# Footer text
footer: >
    Hi there! Follow me on any of my socials and drop by when I'm live to hang out!

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2024  <a href="https://link.zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
